const data = [
  {
    id: "Intro",
    icon: "bxs-book-open",
    p1: "Medicoscript journal considers manuscripts for publication, prepared in accordance with the Guidelines for the Uniform Requirements for Manuscripts Submitted to our journals (see N Engl J Med 1997; 336: 309–315).",
    p2: "Manuscripts are received with the understanding that they have not been published or are not under consideration for publication elsewhere. Manuscripts are accepted based on the recommendations of the referees. Published papers become the sole property of Medicoscript Journals and will be copyrighted by our journal only.",
  },
  {
    id: "Peer Review Process",
    icon: "bx bx-check-shield",
    p1: "Our journals are an open access journal. The journal follows a peer-review process where our expert reviewers provide comments on the quality and content of the submitted articles on the discoveries and current novel developments in the mode of original articles, review articles, case reports, short communications, etc. while making them freely available through online without any restrictions or any other subscriptions to universal researchers.",
    p2: "Every submitted manuscript processed for preliminary quality control check by editorial office followed by external peer review process. Usually, preliminary quality control completes within 7 days and majorly with reference to journal formatting, English and journal scope.",
  },
  {
    id: "Open Access Policy",
    icon: "bx bx-globe",
    p1: "Articles published both in electronic and print versions of our journals may be freely viewed/ copied/ and printed by individual academicians and scholars.",
  },
  {
    id: "Disclaimer",
    icon: "bx bx-shield-quarter",
    p1: "This manuscript is based on original work and had not been published in whole or part, in any print or electronic media or is under consideration of publication in any print or electronic media other than as abstract of conference proceedings. Persons designated as authors must meet all the following criteria.",
    p2: "Declaration of originality, authorship and competing interest on behalf of all authors of the manuscript.",
  },
  {
    id: "Preparation of Manuscripts",
    icon: "bx bx-pencil",
    p1: "The manuscript must be based on original work and not have been published, in whole or in part, in any print or electronic media. The authors must meet all authorship criteria.",
  },
  {
    id: "Title Page",
    icon: "bx bx-bookmark",
    p1: "The title page should include the complete title of the manuscript, the author(s) name(s), the address of the institute where the work was conducted, running title, and the name and address of the corresponding author; 3-8 keywords must be included.",
  },
  {
    id: "Abstract",
    icon: "bx bx-align-left",
    p1: "The abstract should not exceed 250 words. It should be written in complete sentences and should give factual information.",
  },
  {
    id: "Abbreviations",
    icon: "bxs-edit-alt",
    p1: "Abbreviations of units should conform to those shown above.",
    p2: "Other abbreviations and symbols should follow the recommendations in 'A guide for Biological and Medical Editors and Authors' (The Royal Society of Medicine London 1977).",
  },
  {
    id: "References",
    icon: "bx bx-list-ul",
    p1: "A list of all the references cited in the text should be given at the end of the manuscript. The references should be cited according to the Vancouver agreement. They should be numbered consecutively in the order in which they are first mentioned in the text. Identify references in the text by Arabic numerals [in square brackets].",
    p2: "Authors must check and ensure the accuracy of all references cited. All authors should be cited. Abbreviations of titles of medical periodicals should conform to those used in the latest edition of Index Medicus.",
    p3: "The volume of the periodical should be followed by the page number of each reference cited. Some examples are shown below:",
  },
  {
    id: "Journal article",
    icon: "bx bx-book",
    p1: "Roddy P, Goiri J, Flevaud L, Palma PP, Morote S, Lima N. et al., Field Evaluation of a Rapid Immunochromatographic Assay for Detection of Trypanosoma cruzi Infection by Use of Whole Blood. J. Biomed. Res. 2008; 46: 2022-2027.",
  },
  {
    id: "Personal authors’ book",
    icon: "bx bx-user",
    p1: "Carr KE, Toner PG. Cell structure: An introduction to electron microscopy. 3rd Ed Edinburgh Churchill Livingstone 1962.",
  },
  {
    id: "Edited Book",
    icon: "bx bx-book-content",
    p1: "Edited Book Example Content.",
  },
  {
    id: "Chapter in a book",
    icon: "bx bx-book-reader",
    p1: "Chapter in a Book Example Content.",
  },
  {
    id: "Tables",
    icon: "bx bx-table",
    p1: "Tables Example Content.",
  },
  {
    id: "Figures",
    icon: "bx bx-image",
    p1: "Figures Example Content.",
  },
  {
    id: "Article Processing Charges (APC)",
    icon: "bxs-dollar-circle",
    p1: "Note: Average Article Processing Time (APT) is 42 days",
  },
  {
    id: "Galley Proofs",
    icon: "bxs-edit-alt",
    p1: "Unless indicated otherwise, galley proofs will be sent to the first-named author and should be returned within 48 hours of receipt.",
  },
  {
    id: "Reprints",
    icon: "bxs-file",
    p1: "Reprints may be purchased. Order for supply of reprints may be sent while returning the galley proofs after corrections. No reprint/s will be supplied free of charge. Reprint Order Form and Price List will be sent with the galley proofs.",
  },
  {
    id: "Protection of Patients' Rights to Privacy",
    icon: "bxs-lock",
    p1: "Identifying information should not be published in written descriptions, photographs, sonograms, CT scans, etc., and pedigrees unless the information is essential for scientific purposes and the patient (or parent or guardian, wherever applicable) gives informed consent for publication. Authors should remove patients' names from figures unless they have obtained informed consent from the patients. The journal abides by ICMJE guidelines.",
    p2: "Authors, not the journals nor the publisher, need to obtain the patient consent form before the publication and have the form properly archived. The consent forms are not to be uploaded with the cover letter or sent through email to editorial or publisher offices.",
    p3: "If the manuscript contains patient images that preclude anonymity, or a description that has obvious indication to the identity of the patient, a statement about obtaining informed patient consent should be indicated in the manuscript.",
  },
  {
    id: "Copyrights",
    icon: "bxs-copyright",
    p1: "The entire contents of the Medicoscript Journals is protected under Indian and International copyrights. Our Journals, however, grants to all users a free, irrevocable, worldwide, perpetual right of access to, and a license to copy, use, distribute, perform and display the work publicly and to make and distribute derivative works in any digital medium for any reasonable non-commercial purpose, subject to proper attribution of authorship and ownership of the rights. Our journal also grants the right to make small numbers of printed copies for their personal non-commercial use under Creative Commons Attribution-Non-commercial-Share Alike 4.0 International Public License.",
  },
  {
    id: "Referees",
    icon: "bxs-user",
    p1: "Generally, submitted manuscripts are sent to two experienced referees from our panel. The contributors may submit names of three qualified reviewers who have had experience in the subject of the submitted manuscript, but are not associated with the same institution(s) as the contributors nor have published manuscripts with the contributors in the past 10 years.",
    p2: "Medicoscript Journals editors are responsible for deciding which of the articles submitted to the journal should be published in the current volume of the journal. The editor may be guided by the policies of the journal's editorial board and constrained by such legal requirements as shall then be in force regarding libel, copyright infringement and plagiarism.",
    p3: "The editor may at any time evaluate manuscripts for their intellectual content without regard to the nature of the authors or the host institution, including race, gender, sexual orientation, religious belief, ethnic origin, citizenship, or political philosophy of the authors.",
    p4: "The editor must not disclose any information about a submitted manuscript to anyone other than the corresponding author, reviewers, potential reviewers, other editorial advisers, and the publisher, as appropriate.",
    p5: "Unpublished materials disclosed in a submitted manuscript must not be used in an editor's own research without the express written consent of the author.",
    p6: "When genuine errors in published work are pointed out by readers, authors, or members of the editorial board, which do not render the work invalid, a correction (or erratum) will be published as soon as possible. The online version of the paper may be corrected with a date of correction and a link to the printed erratum. If the error renders the work or substantial parts of it invalid, the process of retraction can be initiated. In such cases, the retraction communication with explanations as to the reason for retraction will be published as soon as possible. Consequently, the message about retraction will be indicated on the article page and in the PDF version of the retracted article.",
    p7: "If serious concerns are raised by readers, reviewers, or others about the conduct, validity, or reporting of academic work, the editor will initially contact the authors and allow them to respond to the concerns. If that response is unsatisfactory, allied academies will take this to the institutional level.",
    p8: "Medicoscript Journals will respond to all allegations or suspicions of research or publication misconduct raised by readers, reviewers, or other editors. Cases of possible plagiarism or duplicate/redundant publication will be assessed by the journal. In other cases, allied academies may request an investigation by the institution or other appropriate bodies (after seeking an explanation from the authors first and if that explanation is unsatisfactory).",
    p9: "Retracted papers will be retained online, and they will be prominently marked as a retraction in all online versions, including the PDF, for the benefit of future readers.",
  },
  {
    id: "Duties of Reviewers",
    icon: "bxs-pencil",
    p1: "Peer review assists the editor in making editorial decisions and through the editorial communications with the author may also assist the author in improving the paper.",
    p2: "Any selected referee who feels unqualified to review the research reported in a manuscript or knows that its prompt review will be impossible should notify the editor and excuse themselves from the review process.",
    p3: "Any manuscripts received for review must be treated as confidential documents. They must not be shown to or discussed with others except as authorized by the editor.",
    p4: "Reviews should be conducted objectively. Personal criticism of the author is inappropriate. Referees should express their views clearly with supporting arguments.",
    p5: "Reviewers should identify relevant published work that has not been cited by the authors. Any statement that an observation, derivation, or argument had been previously reported should be accompanied by the relevant citation. A reviewer should also call to the editor's attention any substantial similarity or overlap between the manuscript under consideration and any other published paper of which they have personal knowledge.",
    p6: "Privileged information or ideas obtained through peer review must be kept confidential and not used for personal advantage. Reviewers should not consider manuscripts in which they have conflicts of interest resulting from competitive, collaborative, or other relationships or connections with any of the authors, companies, or institutions connected to the papers.",
    p7: "The editor will take reviewer misconduct seriously and pursue any allegation of breach of confidentiality, non-declaration of conflicts of interest (financial or non-financial), inappropriate use of confidential material, or delay of peer review for competitive advantage. Allegations of serious reviewer misconduct, such as plagiarism, will be taken to the institutional level.",
  },
  {
    id: "Duties of Authors",
    icon: "bxs-pencil",
    p1: "Authors of reports of original research should present an accurate account of the work performed as well as an objective discussion of its significance. Underlying data should be represented accurately in the paper. A paper should contain sufficient detail and references to permit others to replicate the work. Fraudulent or knowingly inaccurate statements constitute unethical behaviour and are unacceptable.",
    p2: "Authors should ensure that submitted work is original and has not been published elsewhere in any language, and if the authors have used the work and/or words of others that this has been appropriately cited or quoted.",
    p3: "Applicable copyright laws and conventions should be followed. Copyright material (e.g. tables, figures or extensive quotations) should be reproduced only with appropriate permission and acknowledgement.",
    p4: "An author should not in general publish manuscripts describing essentially the same research in more than one journal or primary publication. Submitting the same manuscript to more than one journal concurrently constitutes unethical publishing behaviour and is unacceptable.",
    p5: "Proper acknowledgment of the work of others must always be given. Authors should cite publications that have been influential in determining the nature of the reported work.",
    p6: "When reporting experiments on human subjects, indicate whether the procedures followed were in accordance with the ethical standards of the responsible committee on human experimentation (institutional or regional) and with the Helsinki Declaration of 1975, as revised in 2000 (http://www.wma.net/en/30publications/10policies/b3/). Do not use patients' names, initials, or hospital numbers, especially in illustrative material. When reporting experiments on animals, indicate whether the institution's or a national research council's guide for, or any national law on the care and use of laboratory animals was followed.",
  },
  {
    id: "Statistics",
    icon: "bx bx-bar-chart",
    p1: "When possible, quantify findings and present them with appropriate indicators of measurement error or uncertainty (such as confidence intervals). Report losses to observation (such as dropouts from a clinical trial).",
    p2: "Put a general description of methods in the Methods section. When data are summarized in the Results section, specify the statistical methods used to analyze them.",
    p3: "Avoid non-technical uses of technical terms in statistics, such as ‘random’ (which implies a randomizing device), ‘normal’, ‘significant’, ‘correlations’, and ‘sample’. Define statistical terms, abbreviations, and most symbols.",
  },
];

export default data;
